export const auth = {
  AUTHENTICATED: "AUTHENTICATED",
  WECHATAUTH: "WECHATAUTH",
};

export const classes = {
  USER_CLASSES: "USER_CLASSES",
  CLASSES_LOADING: "CLASSES_LOADING",
  ADD_CLASS: "ADD_CLASS",
  FECHING_STUDENTS: "FECHING_STUDENTS",
  CLASS_STUDENTS: "CLASS_STUDENTS",
  CURRENT_HOMEWORK: "CURRENT_HOMEWORK",
};

export const homework = {
  CURRENT_HOMEWORK: "CURRENT_HOMEWORK",
  HOMEWORK_LOADING: "HOMEWORK_LOADING",
};
